use_frameworks!
platform :ios, '8.0'

target 'SNavigationControllerExample' do
  pod 'SNavigationController', :path => '../'

  target 'SNavigationControllerExampleTests' do
    inherit! :search_paths

    
  end
end
